### PR TITLE
Clean js code(fr?)

### PR DESCRIPTION
**Pull request by bluestar-b**
Bruh sorry but I'll test in real environment on morning

### CODE REVIEW

**Comment by blueskychan-dev** [comment]
What do you want?

**Comment by bluestar-b** [comment]
> What do you want?

A performance ☠️☠️☠️☠️☠️
so just wait i test and confirmed

So you will die by w3 standard 🥰🥰🥰🥰

**Comment by blueskychan-dev** [comment]
> > What do you want?
> 
> A performance ☠️☠️☠️☠️☠️
> so just wait i test and confirmed
> 
> So you will die by w3 standard 🥰🥰🥰🥰

Maybe, if you can help, just pull and let me review it.

**Comment by bluestar-b** [comment]
(closed)

**Pull request closed without merging**
