### PR TITLE
check your mailbox

### PR DESCRIPTION
**Pull request by bluestar-b**

### CODE REVIEW

**Comment by bluestar-b** [comment]
Note: in progress + test pr

**Comment by blueskychan-dev** [comment]
Can I preview this pull before merge it?

**Comment by bluestar-b** [comment]
> Can I preview this pull before merge it?

Sure

chrome_screenshot_1687763077639

**Comment by blueskychan-dev** [comment]
did you try change libs or anything else?

**Comment by bluestar-b** [comment]
> did you try change libs or anything else?

Not now 

So i maybe try css framework later...

**Pull request merged**
